name: release
on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v0.0.3, etc.
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile
      - run: bun run build

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Commit dist if changed
        run: |
          if ! git diff --quiet -- cli/dist gh-action/dist shared/dist; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add cli/dist gh-action/dist shared/dist
            git commit -m "chore: build dist for ${{ steps.version.outputs.tag }}"
            git push origin HEAD:main
          fi

      - name: Move major tag (v1, v2, ...)
        run: |
          MAJOR="v$(echo "${{ steps.version.outputs.version }}" | cut -d. -f1)"
          git tag -f "$MAJOR" "${{ steps.version.outputs.tag }}"
          git push -f origin "$MAJOR"
